// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_leadership: dynamic(() => import("./AboutUsLeadership")),
  about_us_mission: dynamic(() => import("./AboutUsMission")),
  about_us_story: dynamic(() => import("./AboutUsStory")),
  about_us_values: dynamic(() => import("./AboutUsValues")),
  bento: dynamic(() => import("./Bento")),
  call_to_action: dynamic(() => import("./CallToAction")),
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  programs_bento: dynamic(() => import("./ProgramsBento")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
  testimonial: dynamic(() => import("./Testimonial")),
};
